import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import type { Pool } from "pg";

function getMigrationsFolder(): string {
  const currentDir = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.resolve(currentDir, "../../drizzle"),
    path.resolve(currentDir, "../drizzle"),
    path.resolve(currentDir, "../../../drizzle"),
  ];
  for (const dir of candidates) {
    if (fs.existsSync(path.join(dir, "meta"))) {
      return dir;
    }
  }
  throw new Error(
    "Could not locate drizzle migrations folder. " +
      `Searched: ${candidates.join(", ")}`,
  );
}

/**
 * Apply Drizzle migrations to create/update the `ai_chatbot` schema and tables.
 * Uses migration files generated by `drizzle-kit generate` from `schema.ts`,
 * so the DDL is always in sync with the Drizzle schema definition.
 */
export async function ensureSchema(pool: Pool): Promise<void> {
  const db = drizzle(pool);
  await migrate(db, { migrationsFolder: getMigrationsFolder() });
}
