"""Focused tests for generated Mason agent configuration and rendering."""

from __future__ import annotations

import ast
import pathlib
import shutil
from typing import cast

import pytest
import tomli

from databricks_mason.agent_config import AgentConfig
from databricks_mason.errors import AgentCliError
from databricks_mason.project_renderer import render_project


def _config(
    *,
    name: str = "support-agent",
    framework: str = "langgraph",
    model: str = "databricks-gpt-5-2",
    instructions: str = "You are a helpful assistant.",
    chat_app_enabled: bool = True,
) -> AgentConfig:
    return AgentConfig(
        name=name,
        framework=framework,
        model=model,
        instructions=instructions,
        chat_app_enabled=chat_app_enabled,
    )


def _write_project(root: pathlib.Path, framework: str = "langgraph") -> pathlib.Path:
    (root / "agent").mkdir(parents=True)
    instruction_argument = "system_prompt" if framework == "langgraph" else "instructions"
    (root / "agent" / "agent.py").write_text(
        'MODEL = "old-model"\n'
        'INSTRUCTIONS = "old instructions"\n\n'
        f"AGENT = dict(model=MODEL, {instruction_argument}=INSTRUCTIONS)\n",
        encoding="utf-8",
    )
    (root / "agent.toml").write_text(
        f'schema_version = 1\n# keep this comment\n\n[agent]\nframework = "{framework}"\n'
        'custom = "preserved"\n\n[extra]\nenabled = true\n',
        encoding="utf-8",
    )
    (root / "pyproject.toml").write_text(
        f'[project]\nname = "agent-{framework}"\nversion = "0.1.0"\n'
        'description = "old description"\n\n[tool.custom]\nenabled = true\n',
        encoding="utf-8",
    )
    return root


def test_agent_config_is_frozen_and_validates_fields():
    assert AgentConfig.__dataclass_params__.frozen is True
    with pytest.raises(AgentCliError, match="name"):
        _config(name="not valid")
    with pytest.raises(AgentCliError, match="framework"):
        _config(framework="unsupported")
    with pytest.raises(AgentCliError, match="instructions"):
        _config(instructions="  ")
    with pytest.raises(AgentCliError, match="boolean"):
        _config(chat_app_enabled=cast(bool, "yes"))


def test_agent_config_write_preserves_other_manifest_content(tmp_path: pathlib.Path):
    project = _write_project(tmp_path)
    path = _config(chat_app_enabled=True).write(project)

    assert path == project / "agent.toml"
    text = path.read_text(encoding="utf-8")
    assert "# keep this comment" in text
    with path.open("rb") as manifest_file:
        manifest = tomli.load(manifest_file)
    assert manifest["agent"] == {
        "framework": "langgraph",
        "custom": "preserved",
        "name": "support-agent",
        "model": "databricks-gpt-5-2",
        "instructions": "You are a helpful assistant.",
        "chat_app_enabled": True,
    }
    assert manifest["extra"] == {"enabled": True}


@pytest.mark.parametrize(
    ("framework", "description", "instruction_argument"),
    [
        ("langgraph", "LangGraph agent generated by Mason", "system_prompt"),
        ("openai", "OpenAI Agents SDK agent generated by Mason", "instructions"),
    ],
)
def test_render_project_uses_safe_literals_and_updates_pyproject(
    tmp_path: pathlib.Path,
    framework: str,
    description: str,
    instruction_argument: str,
):
    project = _write_project(tmp_path, framework)
    config = _config(
        name="quoted-agent",
        framework=framework,
        model='endpoint-"quoted"',
        instructions='Say "hello".\nKeep paths like C:\\tmp safe.',
    )

    render_project(project, config)

    agent_source = (project / "agent" / "agent.py").read_text(encoding="utf-8")
    ast.parse(agent_source)
    assert 'MODEL = "endpoint-\\"quoted\\""' in agent_source
    assert 'INSTRUCTIONS = "Say \\"hello\\".\\nKeep paths like C:\\\\tmp safe."' in agent_source
    assert f"{instruction_argument}=INSTRUCTIONS" in agent_source
    with (project / "pyproject.toml").open("rb") as pyproject_file:
        pyproject = tomli.load(pyproject_file)
    assert pyproject["project"]["name"] == "quoted-agent"
    assert pyproject["project"]["description"] == f"quoted-agent {description}"
    assert pyproject["tool"]["custom"] == {"enabled": True}


@pytest.mark.parametrize("framework", ["langgraph", "openai"])
def test_default_render_preserves_current_framework_template(
    tmp_path: pathlib.Path, framework: str
):
    template_root = pathlib.Path(__file__).resolve().parents[2] / "templates" / f"agent-{framework}"
    project = _write_project(tmp_path, framework)
    shutil.copyfile(template_root / "agent" / "agent.py", project / "agent" / "agent.py")
    original = (project / "agent" / "agent.py").read_text(encoding="utf-8")

    render_project(project, _config(name=f"agent-{framework}", framework=framework))

    assert (project / "agent" / "agent.py").read_text(encoding="utf-8") == original


def test_render_project_refuses_missing_required_files_without_editing(tmp_path: pathlib.Path):
    project = _write_project(tmp_path)
    original = (project / "agent" / "agent.py").read_text(encoding="utf-8")
    (project / "pyproject.toml").unlink()

    with pytest.raises(AgentCliError, match="pyproject.toml"):
        render_project(project, _config())

    assert (project / "agent" / "agent.py").read_text(encoding="utf-8") == original


def test_render_project_requires_template_configuration_constants(tmp_path: pathlib.Path):
    project = _write_project(tmp_path)
    (project / "agent" / "agent.py").write_text('MODEL = "model"\n', encoding="utf-8")

    with pytest.raises(AgentCliError, match="INSTRUCTIONS"):
        render_project(project, _config())
