"""Render validated user configuration into a scaffolded Mason template."""

from __future__ import annotations

import ast
import json
import os
import pathlib
import re
import tempfile

import tomlkit
from tomlkit.exceptions import ParseError

from databricks_mason.agent_config import AgentConfig
from databricks_mason.errors import AgentCliError

_REQUIRED_PROJECT_FILES = (
    pathlib.Path("agent.toml"),
    pathlib.Path("pyproject.toml"),
    pathlib.Path("agent/agent.py"),
)
_ASSIGNMENT_PATTERN = re.compile(r"^(?P<name>MODEL|INSTRUCTIONS)\s*=.*$", re.MULTILINE)
_FRAMEWORK_DESCRIPTIONS = {
    "langgraph": "LangGraph agent generated by Mason",
    "openai": "OpenAI Agents SDK agent generated by Mason",
}


def _read_text(path: pathlib.Path, description: str) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise AgentCliError(f"Could not read {description} at {path}: {exc}.") from exc


def _atomic_write(path: pathlib.Path, content: str) -> None:
    temporary: pathlib.Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as output:
            temporary = pathlib.Path(output.name)
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path)
    except OSError as exc:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        raise AgentCliError(f"Could not render project file at {path}: {exc}.") from exc


def _render_agent(path: pathlib.Path, config: AgentConfig) -> str:
    source = _read_text(path, "agent source")
    values = {"MODEL": config.model, "INSTRUCTIONS": config.instructions}
    found: set[str] = set()

    def replace(match: re.Match[str]) -> str:
        name = match.group("name")
        if name in found:
            raise AgentCliError(f"Agent template at {path} declares {name} more than once.")
        found.add(name)
        return f"{name} = {json.dumps(values[name])}"

    rendered = _ASSIGNMENT_PATTERN.sub(replace, source)
    missing = values.keys() - found
    if missing:
        names = ", ".join(sorted(missing))
        raise AgentCliError(f"Agent template at {path} does not declare {names}.")
    try:
        ast.parse(rendered, filename=str(path))
    except SyntaxError as exc:
        raise AgentCliError(f"Rendered agent source at {path} is invalid: {exc}.") from exc
    return rendered


def _render_pyproject(path: pathlib.Path, config: AgentConfig) -> str:
    try:
        document = tomlkit.parse(_read_text(path, "pyproject.toml"))
    except ParseError as exc:
        raise AgentCliError(f"Could not parse pyproject.toml at {path}: {exc}.") from exc
    project = document.get("project")
    if project is None or not hasattr(project, "__setitem__"):
        raise AgentCliError(f"pyproject.toml at {path} must declare a [project] table.")
    project["name"] = config.name
    project["description"] = f"{config.name} {_FRAMEWORK_DESCRIPTIONS[config.framework]}"
    return tomlkit.dumps(document)


def render_project(project: pathlib.Path, config: AgentConfig) -> None:
    """Render ``config`` into the framework template already scaffolded at ``project``."""
    project_root = pathlib.Path(project).expanduser().resolve()
    missing = [
        str(relative)
        for relative in _REQUIRED_PROJECT_FILES
        if not (project_root / relative).is_file()
    ]
    if missing:
        raise AgentCliError(
            f"Cannot render Mason project at {project_root}: missing required file(s) "
            f"{', '.join(missing)}."
        )

    agent_path = project_root / "agent" / "agent.py"
    pyproject_path = project_root / "pyproject.toml"
    rendered_agent = _render_agent(agent_path, config)
    rendered_pyproject = _render_pyproject(pyproject_path, config)
    _atomic_write(agent_path, rendered_agent)
    _atomic_write(pyproject_path, rendered_pyproject)
